### ISSUE TITLE
Can you add info about how to compile and install on debian 10?

### ISSUE THREAD

**Issue by realtebo** [tealeg/xlsx2csv#16]
Can you add info about how to compile and install on debian 10?

There is no doc at all.
I have no experience of go programs, I've no idea of what to do

**Comment by efeakaroz13** [comment]
Hello I compiled the script for linux you can check this:https://github.com/efeakaroz13/xlsx2csv

**Comment by levinit** [comment]
you can get compiled program file in bin directory
